#!/bin/bash
###################
# mom - My Own Manual
# cos you are your own savior! ;-)
# create your own help files for programs
################### 
#config file
RCFILE=~/.momrc

# setup color variables
attr_is_on=true
color_is_on=true
#color_is_on=false

reset=

bold=
rbold=
dim=
invert=
rinvert=
underlined=
runderlined=
blink=
rblink=

black=
red=
green=
yellow=
blue=
magenta=
cyan=
gray=
dgray=
white=

if $attr_is_on; then
  reset="\E[0m"

  bold='\e[1m'
  rbold='\e[22m'
  dim='\e[2m'
  invert='\e[3m'
  rinvert='\e[23m'
  underlined='\e[4m'  
  runderlined='\e[24m'  
  blink='\e[5m'
  rblink='\e[25m'
fi
if $color_is_on; then
  reset="\E[0m"

  def='\E[39m'
  black='\E[30m'
  red='\E[31m'
  green='\E[32m'
  yellow='\E[33m'
  blue='\E[34m'
  magenta='\E[35m'
  cyan='\E[36m'
  gray='\E[37m'
  dgray='\E[90m'
  white='\E[97m'
# on gray
#  black='\E[30;47m'
#  red='\E[31;47m'
#  green='\E[32;47m'
#  yellow='\E[33;47m'
#  blue='\E[34;47m'
#  magenta='\E[35;47m'
#  cyan='\E[36;47m'
#  white='\E[37;47m'
fi

if [ $# -eq 0 ]; then
  echo -e "Use $red$bold$0$rbold$gray program_name$reset"
  exit
fi

b (){
# save
ATSTAT=("${ATSTAT[@]}" "$1")
echo -e ${!1} 
}

e (){
# remove the last
lastat=$((${#Unix[@]}-1))
if [ $lastat -gt 0 ]; then
  lastat=$(($lastat-1))
  ATSTAT=("${ATSTAT[@]:0:$lastat}")
  echo -e $ATSTAT[$lastat]
else
  ATSTAT=
  echo -e $reset
fi

}

# default color scheme
PROGCOL=$red

if [[ -f $RCFILE ]]; then
  # overwrite color scheme 
  source $RCFILE
fi

echo ${ATSTAT[@]}
b green
echo ${ATSTAT[@]}
echo -e "test $PROGCOL$1$reset"
echo ${ATSTAT[@]}
